# params config

iter:
    batch_size:    48
    epoch:         20
    learn_rate:    0.01
    model_dir:     '../docs/model/checkpoints/'
    model_name:    'default_best.h5'
    model_type:    'CNN-non-static' # only CNN-static, CNN-non-static, CNN-rand valiable
    # gpu_fraction: 0.3
X:
    embedding_dim: 8
Conv1D:
    layer1:
        filters:       32
        filter_size:   3
        padding_mode:   'valid'
        pooling_size:  2 # default 2
        dropout:       0.3
        batch_norm: {momentum: 0.9}
    layer2:
        filters:       64
        filter_size:   3
        padding_mode:   'valid'
        pooling_size:  2 # default 2
        dropout:      0.3
        batch_norm: {momentum: 0.9}
    layer3:
        filters:       128
        filter_size:   2
        padding_mode:   'valid'
        pooling_size:  2 # default 2
        dropout:      0.3
        batch_norm: {momentum: 0.9}
LSTM:
    layer1:
        cell:       128
        return_sequences:   true
        batch_norm: {momentum: 0.9}
        dropout:       0.3
    layer2:
        cell:       128
        return_sequences:   true
        batch_norm: {momentum: 0.9}
        dropout:       0.3
    # layer3:
    #     cell:       128
    #     return_sequences:   false
    #     batch_norm: {momentum: 0.9}
    #     dropout:       0.3
H1:
    dim:         256
    cell: 256
    dropout:     0.3
    # batch_norm: {momentum: 0.9}
Y:
    loss_func:  'mean_squared_error'
    W_regularizer: 0.1
    activity_reg: {l1: 0.1}
    batch_norm: {momentum: 0.9}
